name: Docker Image CI

env: 
  __CHALK_TESTING__: "Yes"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
# Added for Chalk
permissions:
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Chalk
          uses: crashappsec/setup-chalk-action@entitlements
          continue-on-error: true
          with:
            connect: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
